### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by Kyyrick** [FuGu0416/Fishs_Undead_Rising#10]
Hey, love the mod. Just wanted to let you know I've found some issues version: 1.1.0 has a few problems with ticking entities. It looked primarily like Foglet/salamander. Both have caused a server crash multiple times (it seemed like it would primarily happen when they were attempting to aggro players). There are many other mods on the server but I haven't had issue until this version. Just giving you the info in case there isn't enough information yet. 

[crash-2020-08-23_20.41.21-server.txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/5115507/crash-2020-08-23_20.41.21-server.txt)
[crash-2020-08-23_20.47.23-server.txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/5115508/crash-2020-08-23_20.47.23-server.txt)

**Comment by FuGu0416** [comment]
There have been some small fixes regarding this issue after 1.10 was published. Did you have the latest version of 1.1.0?

**Comment by Kyyrick** [comment]
It was not. I did not catch that, my mistake.
