### ISSUE TITLE
Issues with loading a world on 1.16.5

### ISSUE THREAD

**Issue by BeanZephyron** [FuGu0416/Fishs_Undead_Rising#101]
Whenever I attempt to create a new world in order to test the Fish's Undead Rising Mod, I ran into a problem in which my Minecraft menu tells me that there are errors within the datapacks that make it unable to load. I'm not sure if this is a conflict on this mod's end or if something is happening with another mod that I recently updated. By the way, I'm excited to see this mod updated to 1.16.5!

**Comment by FuGu0416** [comment]
https://github.com/FuGu0416/Fishs_Undead_Rising/commit/3ce2da8fffab46590f2cb0c4723f1f03c0916fce should fix this issue.
