### ISSUE TITLE
Raven issues. 1.16.5 latest release. 

### ISSUE THREAD

**Issue by DigitalWendigo** [FuGu0416/Fishs_Undead_Rising#108]
After taming a raven, when you use a stick on it to give it a command, this message appears on the screen. 
Also, they seem unable to perch on a players shoulder. Instead, they flap around on the ground under the players feet.

![2022-04-18_20 50 36](https://user-images.githubusercontent.com/103202053/163999704-788c3e8f-ad04-4fbe-b201-8562f6d584e8.png)

**Comment by FuGu0416** [comment]
the message is fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/0c6dac1135c589a8bb755200ecc3601d538f9d3b
I'll look after the other one later.
