### ISSUE TITLE
[Bug] Banshees cannot attack correctly

### ISSUE THREAD

**Issue by 0BLIQU3** [FuGu0416/Fishs_Undead_Rising#111]
Banshees appear to be extremely inconsistent with actually attacking the player, often diving at the player and simply lingering, playing no attack animation or dealing no damage. During these dives, the banshee will also take fall damage, essentially killing itself as it attempts to attack the player. This coupled with the Banshee's lack of damage with its scream causes it to be a harmless threat to the player.
![banshee](https://user-images.githubusercontent.com/102927126/164128400-224348eb-5fbf-453d-8976-0ba997106a92.png)
[Banshee failing to properly attack the player]

**Comment by Darkmega18** [comment]
-I just see a mostly black screen.-

**Comment by FuGu0416** [comment]
Fixed at https://github.com/FuGu0416/Fishs_Undead_Rising/commit/5e51e51627eb1c73a3e8f7f2e48ffccc329122f0
