### ISSUE TITLE
[1.16.5] Spawning issues

### ISSUE THREAD

**Issue by NixityNull** [FuGu0416/Fishs_Undead_Rising#114]
I cannot seem to find any normal zombies, skeletons, creepers, spiders, husks, etc. They are replaced by an equivalent amount of unburied. If there is a way to allow normal mobs to spawn or if you could add an option to adjust spawn rates, that would be nice.

**Comment by FuGu0416** [comment]
Unburied does not spawn naturally (only from tombstone or Undertaker). Did you use other mods to tweak mob spawning?

**Comment by NixityNull** [comment]
> Unburied does not spawn naturally (only from tombstone or Undertaker). Did you use other mods to tweak mob spawning?

No. I had other mob spawning mods, but very few of them spawned either. there was about 3 sets of tombstones nearby but it didn't excuse the lack of other mobs or the sheer abundance of them in the desert. Regardless, I would still prefer having the ability to change spawn rates and maybe structure gen rarity.

**Comment by FuGu0416** [comment]
Try editing

"Spawn rate of Cemetery [1-10000]": spawn rate of Cemetery, higher = more likely to generate
""Cemetery spawns Unburied occasionally. [0-100]": spawn rate of Unburied in Cemetery, higher = more likely to spawn

in the config file "mod_lavacow.common.toml"
