### ISSUE TITLE
tomb generation bug

### ISSUE THREAD

**Issue by DragonAstemirN** [FuGu0416/Fishs_Undead_Rising#116]
![2022-05-02_18 04 17](https://user-images.githubusercontent.com/94336869/166387929-f61504f2-b186-4376-897e-be2f9945fa01.png)
![Inked2022-05-02_18 04 31_LI](https://user-images.githubusercontent.com/94336869/166388501-7456cee2-6b1d-4306-a5ce-cfb2fddf6b7b.jpg)

**Comment by DragonAstemirN** [comment]
Minecraft 1.16.5-------[Fish's Undead Rising-1.3.2]

**Comment by FuGu0416** [comment]
fixed in c8e2fd1e2b72324159c436d001a73b2e6a95d3d0
