### ISSUE TITLE
Random crash when paired with the mod Performant. Minecraft: 1.16.5. Mod version: 2.0.3

### ISSUE THREAD

**Issue by DigitalWendigo** [FuGu0416/Fishs_Undead_Rising#117]
[latest.log](https://github.com/FuGu0416/Fishs_Undead_Rising/files/8891197/latest.log)
This is the latest log file. 
There is also an issue regarding this opened on the github page of Performant.
https://github.com/someaddons/performant_issues/issues/242 
They suggest it's the parasite, but I honestly can't make out heads or tails out of it.
Let me know if you require more information.

**Comment by FuGu0416** [comment]
https://github.com/FuGu0416/Fishs_Undead_Rising/commit/8590d2fb17274015b8847811823631f40c5e47b3 should fix the error move issue, but I'm not sure if that is the cause.

**Comment by FuGu0416** [comment]
@DigitalWendigo did you still encounter this in the latest version ?
