### ISSUE TITLE
[1.16.5] WorldSettingsImport errors.

### ISSUE THREAD

**Issue by wasdspace** [FuGu0416/Fishs_Undead_Rising#118]
Forge: 1.16.5-36.2.35
Mod version: 2.0.3

When generating the world:
```
[Netty Local Client IO #0/ERROR] [net.minecraft.util.registry.WorldSettingsImport/]: Error adding element: Unknown registry element com.Fishmod.mod_LavaCow.world.gen.WorldGenLargeGlowShroom@cb1c58c
[Netty Local Client IO #0/ERROR] [net.minecraft.util.registry.WorldSettingsImport/]: Error adding element: Unknown registry element com.Fishmod.mod_LavaCow.world.gen.WorldGenCemeterySmall@21c5c68a
```

[latest.log](https://github.com/FuGu0416/Fishs_Undead_Rising/files/8976550/latest.log)
Easy to reproduce. However I still don't know whether it will affect normal play.

**Comment by FuGu0416** [comment]
This should not affect game play, but I'll fix that in the next update anyway.
