### ISSUE TITLE
Ravens Spawning In Misty World Dimension

### ISSUE THREAD

**Issue by dalekfan** [FuGu0416/Fishs_Undead_Rising#12]
This is so sad. They just die instantly. Please fix this. I suggest a mob spawning dimension blacklist.
![2020-09-02_08 12 52_2](https://user-images.githubusercontent.com/49622705/91980179-dd779b00-ecf4-11ea-9a63-f8c40df8c4cb.png)
![2020-09-02_08 12 59](https://user-images.githubusercontent.com/49622705/91980181-dd779b00-ecf4-11ea-899c-e867f1440a57.png)

**Comment by FuGu0416** [comment]
```
    @Override
	public boolean getCanSpawnHere() {
		if(this.dimension == DimensionType.OVERWORLD.getId())
			return super.getCanSpawnHere();
		else return false;
	}
```
Hmm, I think I only missed setting up Raven's condition. Most other mobs were already restricted to spawn in the overworld dimension with the code above.

**Comment by FuGu0416** [comment]
Dimension allow list will be added in the next update.
