### ISSUE TITLE
Crown of Rule [1.16.5]

### ISSUE THREAD

**Issue by Serinexxa** [FuGu0416/Fishs_Undead_Rising#120]
The crown is partially working for me in this version, but doesn't appear to be fully working.
Skeletons are largely neutral- unless touched by the player in which they will briefly attack before returning neutral.

However, I cannot seem to activate the process in which these former enemies come to your aid.
(Tested on Forsaken, vanilla Skeleton, modded skeletons)

There is also a minor visual error when the crown is equipped- in which the front part of the crown also appears on the side of the player's head.
![image](https://user-images.githubusercontent.com/93160082/185303546-b3bb1fe8-f72f-4f84-aa02-7ad8f93dc4e4.png)

**Comment by FuGu0416** [comment]
should be fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/4c6fb06434e5c5ccb28e8b44ea222a1ab79d2169 and https://github.com/FuGu0416/Fishs_Undead_Rising/commit/506ee16b4ed8c2fc26aefe8837b7fa833c1b7876
