### ISSUE TITLE
一些關於1.16.5版本的反饋

### ISSUE THREAD

**Issue by msjlwlb** [FuGu0416/Fishs_Undead_Rising#121]
這是我最喜歡的模組了，這些怪物的模型都很棒， 感謝作者將它更新到了1.16版本，以下是我在玩1.16.5時發現的一些問題：
1.溫迪戈無法向遠處目標跳躍，雙手攻擊也不能破盾和造成1.5倍傷害
2.骷髏王不能召喚被遺忘者
3.存在 一個介於疫豬近戰距離和使它蓄力衝撞的距離之間的距離，站在這個距離會使它無法攻擊，另外作者是不是忘了給疫豬加上那兩點護甲
4.神聖手榴彈不能對不死族造成3倍傷害並燃燒
5.巨蜂和翼生獸被其他生物攻擊不會還手

**Comment by FuGu0416** [comment]
已修正於 https://github.com/FuGu0416/Fishs_Undead_Rising/commit/924b01fc432b4c238c3e81f5a2e499d0faef8762

**Comment by msjlwlb** [comment]
> 已修正於 [924b01f](https://github.com/FuGu0416/Fishs_Undead_Rising/commit/924b01fc432b4c238c3e81f5a2e499d0faef8762)

看起來您也沒有放棄1.12.2版本的更新，這個版本還是非常受歡迎的。 所以我再補充一下：第五個問題也存在於1.12.2版本。
