### ISSUE TITLE
Glowshroom is created ignoring the config.

### ISSUE THREAD

**Issue by SuperTiru** [FuGu0416/Fishs_Undead_Rising#122]
![image](https://user-images.githubusercontent.com/108540864/193637397-048e1da4-ee77-4e76-851f-93722bd376a3.png)
I set the spawn rate of glowshroom to 0 without entering any mod other than fish undead rising mod, but ignored the config and the glowshroom is continuously created.
I am currently using 1.16.5 forge and mod 2.1.0 version.

**Comment by FuGu0416** [comment]
fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/bcad87b1b32dcc8f3ce3056bff89af93ede48664
