### ISSUE TITLE
Ticking Banshee Crash

### ISSUE THREAD

**Issue by Hollow024** [FuGu0416/Fishs_Undead_Rising#126]
Sever start ticking when a banshee pass through blocks
I'm currently using Fish's Undead Rising 2.1.1
![image](https://user-images.githubusercontent.com/119385420/205826589-5d1f0c02-7c5f-4783-b9fd-9fa433ac2525.png)

Crash Report:
[crash-2022-11-11_16.42.35-fml.txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/10162993/crash-2022-11-11_16.42.35-fml.txt)

**Comment by FuGu0416** [comment]
It seems that another mod triggers the crash.
> 	Mod File: illuminations-forge-1.16.5-0.0.4.11.jar
	Failure message: Illuminations has class loading errors
		java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/model/EntityModel
	Mod Version: 1.16.5-0.0.4.11
	Mod Issue URL: https://github.com/dimadencep/Illuminations-forge/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.model.EntityModel

**Comment by Hollow024** [comment]
Thanks, it Was just a illuminations config

**Comment by Hollow024** [comment]
server keep crashing for the same reason without illuminations
now this is the crash report:
[crash-2022-12-06_10.55.13-server.txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/10167067/crash-2022-12-06_10.55.13-server.txt)

**Comment by FuGu0416** [comment]
https://github.com/FuGu0416/Fishs_Undead_Rising/commit/5cc90e9cc435f6abf7704cb110a0f8f2d51023a4 should this issue
