### ISSUE TITLE
[Suggestion]Compatibility with Curios API

### ISSUE THREAD

**Issue by 1mtwtfss1** [FuGu0416/Fishs_Undead_Rising#129]
Could you please making Molten Heart, Soul Fire Heart and Golden Heart can be put in Curios API's shots?
Like what the mod had done in 1.12.2 with Baubles.
And if you can make them can be put in any kinds of shots, it will be better. :D
Thank you~

**Comment by FuGu0416** [comment]
added in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/55d2a92bbccda48978b9e612b96cce87de0c3d05
