### ISSUE TITLE
Crash after entering the world

### ISSUE THREAD

**Issue by Kasualix** [FuGu0416/Fishs_Undead_Rising#130]
[crash report](https://pastebin.ubuntu.com/p/XCrNQ9HcTX/)
[maybe related code](https://github.com/FuGu0416/Fishs_Undead_Rising/blob/ab027720110d6c1992f5a4f4053332da614bf17c/forge-1.16.5-36.2.6-mdk/src/main/java/com/Fishmod/mod_LavaCow/events/EventHandler.java#L537)

**Comment by FuGu0416** [comment]
They was caused by Minecraft trying to spawn an entity in a chunk with 0 spawn weight.
Mind if I check your config files?

**Comment by Kasualix** [comment]
ok, here it is: https://pastebin.ubuntu.com/p/m8qQbpbhyY/

**Comment by Kasualix** [comment]
I deleted this config file and relaunched my game and it works, thank you!
