### ISSUE TITLE
Incompatible with Does Potato Tick

### ISSUE THREAD

**Issue by Kasualix** [FuGu0416/Fishs_Undead_Rising#131]
[Does Potato Tick](https://github.com/MCTeamPotato/DoesPotatoTick)
Crash report:
ghostbomb: https://pastebin.ubuntu.com/p/33HdCm6MXv/
holygrenade: https://pastebin.ubuntu.com/p/BH4T6d2Ptf/
sonicbomb: https://pastebin.ubuntu.com/p/T3tcwjbfjT/
When I was using "/summon mod_lavacow:ghostbomb/" or "/summon mod_lavacow:holygrenade" or "/summon mod_lavacow:sonicbomb", the game crashed.
Is there a way to get compat?

**Comment by FuGu0416** [comment]
https://github.com/FuGu0416/Fishs_Undead_Rising/commit/e9931b01ef9bdb19c2c030b7ec1a3a2d02e063c8 Should fix this issue
