### ISSUE TITLE
Mimicrabs inside slabs

### ISSUE THREAD

**Issue by xJon** [FuGu0416/Fishs_Undead_Rising#133]
![image](https://user-images.githubusercontent.com/8945347/235325151-d60ccc4e-cd59-449c-b5a9-e4fa8cf4fd2f.png)
Sus!

**Comment by FuGu0416** [comment]
fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/b66257174d2f450d31787f7230deb8985c77179f
