### ISSUE TITLE
[Suggestion] Just Enough Resources integration

### ISSUE THREAD

**Issue by xJon** [FuGu0416/Fishs_Undead_Rising#134]
Having integration with JER would be very useful for the mod's playability, as there are many special drops from specific mobs that require opening the wiki every time. The wiki is great though!

**Comment by FuGu0416** [comment]
fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/7587c00d7905873abf52422b292c4c39f9c20082, should be working in the next update.
![2023-08-17_22 34 40](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/17677281/0feebb76-b343-4d7b-ab30-4e349112117e)

**Comment by xJon** [comment]
No chance for a 1.12.2 backport? :)

**Comment by xJon** [comment]
I was specifically asking as I plan to add your mod to Hexxit II, but I fully understand ):

**Comment by FuGu0416** [comment]
Hmm... JER integration seems to be much more complicated in 1.12.2 than 1.16.5. 
JER 1.16.5 automatically import all loot tables where JER in 1.12.2 you have to manually import them.
.
Example: https://github.com/Daveyx0/PrimitiveMobs/blob/master/src/main/java/net/daveyx0/primitivemobs/modint/PrimitiveMobsJERIntegration.java

**Comment by xJon** [comment]
Hmm, indeed it seems more complicated in 1.12.2 - feel free to drop it

**Comment by FuGu0416** [comment]
supported in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/08a5268bfb35a591739239bf2b65ccbb65cb09e7
