### ISSUE TITLE
[Suggestion] Config option for disabling root advancement chat announcement

### ISSUE THREAD

**Issue by xJon** [FuGu0416/Fishs_Undead_Rising#135]
Mods' advancements upon joining the world being printed to chat can be fun but also overwhelming in big modpacks. I'm aware the advancement file can be edited, but a proper config option would be preferable!

**Comment by FuGu0416** [comment]
Probably just adding the rule `/gamerule announceAdvancements false`，or edit the `assets\mod_lavacow\advancements\mod_lavacow\root.json` directly, as it's quite complicate to config json files.
