### ISSUE TITLE
[1.12.2] Raven items often can't be collected

### ISSUE THREAD

**Issue by xJon** [FuGu0416/Fishs_Undead_Rising#136]
https://user-images.githubusercontent.com/8945347/235379031-4e1b3ce4-b6be-4061-b21c-aa3a80d0e75a.mp4

It does work sometimes as you can see some loot in the hotbar, but often it does not for some reason.
Tested with only Fish's Undead Rising installed & with default configuration.

**Comment by xJon** [comment]
Items the Ravens collect due to them being dropped in the world always seem to be collectable by interacting with them (unlike the ones from the loottable).

**Comment by FuGu0416** [comment]
1.12.2 is no longer under maintenance unless it encounter some serious crush.

**Comment by FuGu0416** [comment]
Are those ravens tamed or wild?

**Comment by xJon** [comment]
@FuGu0416 They were all tamed. Are you able to reproduce the issue?

**Comment by FuGu0416** [comment]
should be fixed in the latest commit.
