### ISSUE TITLE
[Suggestion] Support Red Sand biome for Desert Tombs

### ISSUE THREAD

**Issue by xJon** [FuGu0416/Fishs_Undead_Rising#137]
![image](https://user-images.githubusercontent.com/8945347/236048545-9a206e06-d4c9-48b7-8fb3-17500355a105.png)

Taken in a Traverse Red Desert biome (1.12.2).

**Comment by FuGu0416** [comment]
added in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/41da255e37ba225cfef5cba1ece017f59b279995
![2023-09-03_00 33 15](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/17677281/78bc15f5-b0b9-4501-b402-421abf28d700)
