### ISSUE TITLE
[1.12.2] Ravens picking up block items rendering seems off

### ISSUE THREAD

**Issue by xJon** [FuGu0416/Fishs_Undead_Rising#138]
![image](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/8945347/095eae2d-4889-4a74-b214-1f2fa959e57d)

**Comment by FuGu0416** [comment]
1.12.2 is no longer under maintenance unless it encounter some serious crush.

**Comment by FuGu0416** [comment]
Should look normal now.
![2023-08-29_00 39 49](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/17677281/478da2f1-b8d9-4fa6-9767-a622312ecbb7)
