### ISSUE TITLE
[1.12.2] Killing the Skeleton King can spawn a double chest, turns into single chest on right click

### ISSUE THREAD

**Issue by xJon** [FuGu0416/Fishs_Undead_Rising#139]
As the title states. Not a big deal but I figured to report it

**Comment by FuGu0416** [comment]
Thanks, but 1.12.2 is no longer under maintenance unless it encounter some serious crush.

**Comment by FuGu0416** [comment]
should be fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/1d371d97f6f97669f4c6b6e1ae513978d5d87e22
Also backporting a config option: "Should Skeleton King drop its loots inside a chest".
