### ISSUE TITLE
[1.16.5] Dissapearing tooltip

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [FuGu0416/Fishs_Undead_Rising#140]
Using Fish's+Undead+Rising-2.2.0.jar. As soon as I break a block the blue tooltip dissapears:

Before breaking block:
![image](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/3938423/89a2bacb-b188-4ab2-a665-228dec822204)

After breaking block:
![image](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/3938423/0baf986d-546f-4461-b616-1a6f1e9d70a0)

Edit:

It's seems to be a problem with JEI somewhat. I removed everything but Fish's+Undead+Rising-2.2.0.jar and jei-1.16.5-7.8.0.1009.jar . And JEI doesn't work: 

![image](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/3938423/d916b8d1-6da3-4f1a-bd04-961fa319abe1)

No Fish's+Undead+Rising-2.2.0.jar **and only** jei-1.16.5-7.8.0.1009.jar, and JEI works:

![image](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/3938423/687119a4-d219-4c9b-9e27-f90f4eaeae66)

**Comment by Unrepentant-Atheist** [comment]
With Fish's+Undead+Rising-2.1.3.jar JEI works, and the blue tooltip doesn't dissapear.

Something wrong with Fish's+Undead+Rising-2.2.0.jar

**Comment by FuGu0416** [comment]
Fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/04c4ef8503283fe491a3883c145e9288cc1b6f41
