### ISSUE TITLE
[1.16.5] Invisible Tools/Weapons with 2.2.1

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [FuGu0416/Fishs_Undead_Rising#141]
Latest build fixes https://github.com/FuGu0416/Fishs_Undead_Rising/issues/140 but introduces another bug: No tools / weapons / anything that is held by the player is visible.

**Comment by FuGu0416** [comment]
Can you provide launching log as well as pictures? It seems working normal on my computer.

**Comment by Unrepentant-Atheist** [comment]
I don't know what happend. Seemed to be a fluke. Works now.
