### ISSUE TITLE
[Suggestion] Mummies spawning at pyramids and tombs in 1.12.2

### ISSUE THREAD

**Issue by IcarussOne** [FuGu0416/Fishs_Undead_Rising#146]
Pretty simple addition that I liked, it would be nice to see this in 1.12.2 as well!

**Comment by FuGu0416** [comment]
Unlike v1.16, the function of adding entity spawned inside structures seems to be not available in v1.12.

**Comment by IcarussOne** [comment]
That's okay, I forgot that 1.12 didn't had this sort of feature. Very happy with everything else so far though!
