### ISSUE TITLE
1.16 捕夢網dreamchtcher失效

### ISSUE THREAD

**Issue by 2929762171** [FuGu0416/Fishs_Undead_Rising#153]
配置文件有耐久度設定，然而遊戲裡無耐久數值，睡覺後也沒有怪物生成
![image](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/98941945/a08cced2-b883-4ddf-a6bf-786b374a8fd4)

**Comment by FuGu0416** [comment]
這是在哪個版本上遇到問題呢?

**Comment by 2929762171** [comment]
> 这是在哪个版本上遇到问题呢？

1.16.5的9月最新版

**Comment by FuGu0416** [comment]
已於 https://github.com/FuGu0416/Fishs_Undead_Rising/commit/a082c183b870471e3266508f724bc2952922a5a9 修正
