### ISSUE TITLE
1.12.2 Game crash with parasite's metamorphosis

### ISSUE THREAD

**Issue by Surestmantis** [FuGu0416/Fishs_Undead_Rising#155]
It seems when a parasite starts their metamorphosis, when the cocoon is about to burst the game simplys intantly crashes. 

[crash-2023-10-15_11.59.56-server.txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/12909888/crash-2023-10-15_11.59.56-server.txt)

Version 1.4.0 was the one being used.

**Comment by FuGu0416** [comment]
Fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/pull/157/commits/b939a1c376c569c5028fc903d21faa35caa639c4
