### ISSUE TITLE
[問題]1.16.5-2.3.0

### ISSUE THREAD

**Issue by 2929762171** [FuGu0416/Fishs_Undead_Rising#159]
【1】黃金之心失效
2.2.2版本時正常，更新後失效
【2】木乃伊魚提示缺失
![image](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/98941945/eb2fe10a-2d7d-4420-9289-f9adc5ba7e27)

**Comment by FuGu0416** [comment]
木乃伊魚敘述部分會再修正，不過黃金之心的部分我這邊測試是正常的，想請問說是否有可能是與其他模組發生衝突?

**Comment by 2929762171** [comment]
在發issue之前發現捕夢網也失效，而且移除其他所有模組之後會變為正常，現在正在排查

**Comment by 2929762171** [comment]
黃金之心受此設定影響，如果生命恢復為false，會導致裝備修復隨之失效
![image](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/98941945/8e8d23bc-3fec-4b8a-b473-92b7ab1afe39)

**Comment by 2929762171** [comment]
捕夢網與quark的增強睡眠衝突
![image](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/98941945/b7f07de5-802e-4639-9540-2b9634727dcf)

**Comment by FuGu0416** [comment]
捕夢網的觸發仰賴 Forge 的 PlayerWakeUpEvent 事件，而 Quark 的增強睡眠似乎會導致 PlayerWakeUpEvent 不被觸發，因此導致捕夢網失效

**Comment by 2929762171** [comment]
可以
