### ISSUE TITLE
[Suggestion] A blocklist for entities that will not drop intestines

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#16]
As a universal drop, there can be a lot of weird inconsistencies with intestine drops. Pretty bizarre and immersion breaking to have things like snails, golems or elemental creatures, and clearly skeletal undead dropping intestines. A config with a blocklist would allow easy removal of the offending mobs' intestine drops without having to edit a hundred different loot tables.

**Comment by democat3457** [comment]
@SandwichHorror @FuGu0416 can be closed

**Comment by FuGu0416** [comment]
I'll close issues after merging 1.12.2_Dev branch back to master.
