### ISSUE TITLE
[建議]1.16 骸骨大劍傷害形式

### ISSUE THREAD

**Issue by 2929762171** [FuGu0416/Fishs_Undead_Rising#161]
目前的骸骨大劍百分比額外傷害無視護甲，並且某些反傷效果也能觸發骸骨大劍的這個，
希望新增一個配置項，可以決定保持現狀，或者是改為普通的傷害加成，能夠被其他效果減免

**Comment by FuGu0416** [comment]
修正於https://github.com/FuGu0416/Fishs_Undead_Rising/commit/85ff6fb5ca3713c695a78ad033cf2d0266fed091
骸骨大劍額外傷害就直接改成會受到傷害減免了，其他傷害也一併改為會受到減免，包括：
- 『惡疫』透過鋒利附魔套用於召喚物身上的傷害加成
- 夜嘆透過鋒利附魔套用於召喚物身上的傷害加成
- 聖甲蟲權杖透過鋒利附魔套用於召喚物身上的傷害加成
- 飢荒套裝效果附加的額外傷害
- 鬼靈匕首附加的額外傷害
