### ISSUE TITLE
Mushrooms don't have separated configs for generation

### ISSUE THREAD

**Issue by B-Wither** [FuGu0416/Fishs_Undead_Rising#164]
Using 1.4.1 in 1.12.2, there is no config other than glowshroom. I want to stop that because these mushrooms generated in other dimensions (Prehistoric Nature for example)

**Comment by FuGu0416** [comment]
Added in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/aaeb697efe1b8b785d385da806e587b3ec35d934
