### ISSUE TITLE
Ghost ray Causes memory allocation error

### ISSUE THREAD

**Issue by River25** [FuGu0416/Fishs_Undead_Rising#166]
I have had to disable ghost rays from the end as for some reason they cause my allocated memory to spike and constantly go up until my game crashes. This also applies to ghost rays in the over world but only is noticeable for the end. There also might be a similar issue with the flying ghost enigma moths though I disabled both when trying to fix the issue and the issue only went away when I disabled ghost ray spawns. I am in 1.12.2 newest version

**Comment by FuGu0416** [comment]
Do you have the crash log?

**Comment by FuGu0416** [comment]
should be fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/158ecf336425149d5765781f4b19d0dc7a3ac835
