### ISSUE TITLE
Thorned effect does not make you immune to cactus and Thorns enchantment damage

### ISSUE THREAD

**Issue by IcarussOne** [FuGu0416/Fishs_Undead_Rising#167]
In the latest versions of 1.12 and 1.16, the Thorned effect doesn't prevent any affected entity from taking cactus or Thorns enchantment damage like it is intended to do.

**Comment by FuGu0416** [comment]
should be fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/e03ebeba92cbfc71c8bd337f7ca99a3ddc8c10a3 & https://github.com/FuGu0416/Fishs_Undead_Rising/commit/9ab4f01fa576ec43d430ffdb7cce0cd00e12bc30
