### ISSUE TITLE
[1.12] Baby salamanders sometimes act like their adult variants when spawning

### ISSUE THREAD

**Issue by IcarussOne** [FuGu0416/Fishs_Undead_Rising#169]
Only affects the 1.12 version. Sometimes when a baby salamander spawns, it'll end up with the same hitbox and attack with multiple projectiles rather than just one as if it were the adult counterpart.
![salamanders](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/135455255/caefc4f4-2f10-49aa-a90b-1c265c530091)

**Comment by FuGu0416** [comment]
should be fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/2d228d483ba2e6bd27fbdc1a5e9687846d23b2eb
