### ISSUE TITLE
[1.12] Crown of Rule has a bugged texture when equipped on your character

### ISSUE THREAD

**Issue by IcarussOne** [FuGu0416/Fishs_Undead_Rising#170]
The Crown of Rule item will have a bugged texture to the side while it is equipped. This doesn't occur in the 1.16 version.
![crown](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/135455255/a93aba33-e0ac-47f2-9b07-88f435685ba3)

**Comment by FuGu0416** [comment]
This could be synced from 1.16 as it had the same issue before but got fixed afterward.

**Comment by FuGu0416** [comment]
fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/6d30fec488d2664b4aa2e3d98cdc35e34cab96aa
