### ISSUE TITLE
[1.12] Tamed Salamander's saddle floats while sitting

### ISSUE THREAD

**Issue by IcarussOne** [FuGu0416/Fishs_Undead_Rising#171]
When adding a saddle to a tamed salamander and making it sit in the 1.12 version, it'll not be properly attached to the salamander unlike the 1.16 version (the bottom screenshot).
![saddle1](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/135455255/13ad6df5-3f2b-474e-b6e6-4dd32782d048)
![saddle2](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/135455255/606d3edc-78d5-4259-a3c3-79b3a849eebe)

**Comment by FuGu0416** [comment]
fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/9400b25f5a6b540f3eee5e7984a883f83328d52a
