### ISSUE TITLE
[1.12] Texture layer problem on armored zombies

### ISSUE THREAD

**Issue by IcarussOne** [FuGu0416/Fishs_Undead_Rising#173]
This happens on the mod's armored zombies, this doesn't occur in the 1.16 version.
___

![armor2](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/135455255/9d1c2c8d-9f98-4524-b8ad-32228be16eca)

**Comment by FuGu0416** [comment]
fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/43c6fe79e32a35e4dbb547aef1a1c862301e9ae2
