### ISSUE TITLE
Undertaker attack animation cuts off halfway (?)

### ISSUE THREAD

**Issue by IcarussOne** [FuGu0416/Fishs_Undead_Rising#175]
Whenever the Undertaker attacks, it looks like it's trying to perform a swing attack but it cuts off halfway through not sure if this is intentional. Affects both 1.12 and 1.16.

**Comment by FuGu0416** [comment]
fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/7bfc5ad83230d159688a73098a72fc1b9927fb27 and https://github.com/FuGu0416/Fishs_Undead_Rising/commit/619b4f892a105adeb43cb4da93b6dcd7164d2e09
