### ISSUE TITLE
[Suggestion] Swarmer Launcher Improvements

### ISSUE THREAD

**Issue by IcarussOne** [FuGu0416/Fishs_Undead_Rising#176]
Currently swarmers fired from the Swarmer Launcher don't do anything when they land on the ground. Having them aggressively attack everything on sight would be a really nice improvement to this weapon.

**Comment by FuGu0416** [comment]
added in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/08ad38ac4bec6b6cf203e4c2c7f4283a3bb0bc65
This enables them to jump onto targets on land. Though they still attack injured entities only.
