### ISSUE TITLE
[1.12.2] Grave generation in trees

### ISSUE THREAD

**Issue by xJon** [FuGu0416/Fishs_Undead_Rising#177]
![image](https://github.com/FuGu0416/Fishs_Undead_Rising/assets/8945347/b878aa08-a742-465b-93bd-afb95c6a341c)

Ancient tradition or bug?

**Comment by FuGu0416** [comment]
fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/7bfc5ad83230d159688a73098a72fc1b9927fb27
