### ISSUE TITLE
Summoned mobs can suffocate in walls or under blocks

### ISSUE THREAD

**Issue by IcarussOne** [FuGu0416/Fishs_Undead_Rising#178]
This is especially noticeable with Avatons where it can summon wetas under blocks making them suffocate to death and it happens more often in small rooms. A solution to this might not be an easy one?

**Comment by FuGu0416** [comment]
This should fix the issue. I'll update this to all the summoning behaviors later.
https://github.com/FuGu0416/Fishs_Undead_Rising/commit/16d9d46851c04910945a0baaf89d6e83a6132aa4
