### ISSUE TITLE
Config option to disable enchantments doesnt remove JEI or books with these enchantments

### ISSUE THREAD

**Issue by KnightCa** [FuGu0416/Fishs_Undead_Rising#181]
What happens: After setting the enable enchantment option to false, I am still able to see them in JEI and have books with the enchantments

Adding new enchantment (existing property will be preserved). [false/true]
    B:"enable enchantment"=false

Desired solution:

- Configuration would have a list of each enchantment, as well as it's max enchantment level.

#
    "enabled enchantments" {
        B:Corrosive=true
        B:Lifesteal=true
        B:Poisonous=true
    }

    # enchantment levels
    #--------------------------------------------------------------------------------------------------------#
    # Maximum levels of each enchantment

    "enchantment levels" {
        # Min: 1
        # Corrosive Max 5
        I:Corrosive=5
        # Lifesteal Max 3
        I:Lifesteal=3
        # Poisonous Max 3
        I:Poisonous=3
        
-  When a Enchantment is set to false, the Enchantment is:
   - Removed from any item in the game that bears the enchantment (book, sword, etc) _(they still appear)_
   - Removed from JEI _(they still appear)_
   - Removed from Anvil recipes _(already does this)_
   - Removed from being found in any loot tables (treasure chest, mob drops) _(unconfirmed behaviour)_
   - Removed from being found in a librarian to trade with _(unconfirmed behaviour)_

Version of Fish's Undead Rising used: Fish's Undead Rising-1.4.2
Minecraft version: 1.12.2

**Comment by FuGu0416** [comment]
Yes, they won't be removed from existing enchanted book / equipment. It's too resource consuming to check all of the enchanted books and equipment one by one, and removing the enchantments' ID from registration isn't a recommended solution either.

The config is intended to only banning the enchantments from appearing afterwards but existing ones stay.
