### ISSUE TITLE
[1.12.2] tamed wetas won't farm

### ISSUE THREAD

**Issue by fruitbowlvoid** [FuGu0416/Fishs_Undead_Rising#183]
i'm not sure if the issue only occurs on servers since i haven't tested it on singleplayer. i can set a tamed weta to wander and it will farm crops as normal, but if i disconnect from the server and reconnect, my wetas (still set to wander) stop trying to harvest crops until i cycle through their modes to "refresh" their wander mode. it pretty much completely breaks their intended use for auto-farming

**Comment by FuGu0416** [comment]
Will be fixed in both 1.12.2 & 1.16.5 ver.
