### ISSUE TITLE
[1.16.5] Fish's Undead Rising MOD The Life Steal enchantment (I-III) crashes the game

### ISSUE THREAD

**Issue by SrTortuga** [FuGu0416/Fishs_Undead_Rising#184]
If a villager from the Comes Alive Reborn Mod that has any weapon with the Lifesteal enchant attacks any mob to regenerate health, the game will crash.
As a curious fact, there is a mod called Wonderful Enchantments that has a similar enchantment called Leech and I have tested it by enchanting a sword and giving it to a villager from the Minecraft Comes Alive Reborn mod and the enchantment does not crash the game and works perfectly, maybe this information helps to fix the Lifesteal crash faster. I would really appreciate it if you could fix it.
[crash-2024-08-07_16.21.27-server.txt](https://github.com/user-attachments/files/16716217/crash-2024-08-07_16.21.27-server.txt)
[crash-2024-08-07_16.29.22-server.txt](https://github.com/user-attachments/files/16716218/crash-2024-08-07_16.29.22-server.txt)
[crash-2024-08-07_17.56.36-server.txt](https://github.com/user-attachments/files/16716219/crash-2024-08-07_17.56.36-server.txt)
[crash-2024-08-22_13.07.41-server.txt](https://github.com/user-attachments/files/16716220/crash-2024-08-22_13.07.41-server.txt)
[crash-2024-08-22_13.31.51-server.txt](https://github.com/user-attachments/files/16716221/crash-2024-08-22_13.31.51-server.txt)

**Comment by FuGu0416** [comment]
Will be fixed in both 1.12.2 & 1.16.5 ver.
