### ISSUE TITLE
[Suggestion/Bug?] Banshee Melee Attack Animation

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#23]
When the banshee does not use its scream, it simply bumps into its target by moving forward, inflicting damage. Having a simple "arm swipe" like the vanilla zombie would be greatly appreciated to visually communicate that the banshee has just made/is making a melee attack.

**Comment by FuGu0416** [comment]
Added in ver 2.0.0
