### ISSUE TITLE
[Suggestion] Configure Range of Weta Hoe's Crop Harvesting

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#28]
While the Weta Hoe is useful, Quark and a few other mods give the "3x3 crop harvest" ability to **all hoes by default.** Having the ability to set the Weta hoe harvesting range to a larger range such as 5x5, 7x7, or even higher would mean that the hoe wouldn't be made irrelevant by a wooden hoe simply due to some other mod.

**Comment by FuGu0416** [comment]
Weta Hoe is removed in the newer version cause a bucket of water works better than it.
