### ISSUE TITLE
[Bug] Unburied lack melee attack animation

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#31]
They just walk forward with arms outstretched. Since their model is the same base as the Frigid/Mycosis, and those mobs' melee attack animations _do_ work, hopefully this isn't tough to fix.

**Comment by FuGu0416** [comment]
Mine works fine though.

**Comment by FuGu0416** [comment]
Should already been fixed in the current version
