### ISSUE TITLE
[Suggestion] Vespa cocoon uses NBT data for "evolution" rather than hardcoded timer

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#33]
You already know about this idea, but I figured I'd "transfer" it to the issue tracker so you can update it as finished, not going to happen, etc.

An NBT data for the metamorphosis like {Life:200s}, where the "Life" determines the time before hatching in ticks, would be cool for custom spawning mechanics - you could have a "vespa nest" with dormant cocoons, and so on. With this in place, maybe you could offer an additional config option for how long it takes a cocoon to hatch into a vespa.

**Comment by FuGu0416** [comment]
Should already been fixed in the current version
