### ISSUE TITLE
[Suggestion]Configuration of Raven/Seagull Loot Generation

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#34]
Having the ability to set what items can appear for seagull/raven/emperor raven, how often (X% chance every Y seconds), or potentially even the weight of each item (like it is for the intestine loot table or Dreamcatcher spawn list) would be excellent for a variety of reasons - buffing the birds with new items, putting in rare goodies, nerfing the default loot, removing fish but adding enchanted fishing books and other fishing loot, etc.

Also, I realize I'm totally clogging up your issue tracker here. I'm sorry for submitting a hundred issues, I just don't want to forget them and I would've ended up posting them all on the discord anyway where they might have gotten lost.

**Comment by Avlyssna** [comment]
I'll take a look into adding a configuration option for this tomorrow. Thanks for the suggestion!
