### ISSUE TITLE
Wonderful server crash every now and then caused by Fish_Undead_Rising ticking entity :D

### ISSUE THREAD

**Issue by lllMohandarlll** [FuGu0416/Fishs_Undead_Rising#35]
I updated to Fish's Undead Rising-1.2.0, the new mobs seemed pretty cool (and they are), but then the server began to crash every now and then... In the first log there was something about TickCentral too so I disabled the mod in the hope it was its fault, but no... the scarecrow entity for some reason in these circumstances give some issue...
**EDIT:** looking more accurately I may have a clue on what is going on... Scaling Health adds some potion effect to mobs when they are chosen to become blights, which may explain the "_at net.minecraft.entity.EntityLivingBase.addPotionEffect(EntityLivingBase.java:751)_"

crash log:
https://pastebin.com/3UgSLxHw

server log:
https://pastebin.com/

I hope this repo is active, I really wish to keep this mod on its last update...

**Comment by FuGu0416** [comment]
Work fine on both my client & server test, might be interfered by other mods.

This is the line reported in the crash report
`((EntityLivingBase)this.getAttackTarget()).addPotionEffect(new PotionEffect(MobEffects.WITHER, 4 * 20 * (int)f, 1));` 
It seems that the wither effect becomes unknown somehow.

**Comment by lllMohandarlll** [comment]
I've tryied disabling the potion effects on mobs from Scalin Health meanwhile, let's see how is it going..
Oh since we're here, was you already aware that the bone sword damage cap in the config doesn't work at all? I tryied to notify that on curseforge page too
