### ISSUE TITLE
[Bug][1.2.1]Ptera and Ghost Ray Lack Wandering/Pathfinding AI

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#37]
When spawned or summoned, the Ghost Ray and Ptera simply float in place. The Ghost Ray does not actually attempt to flee, but just gets hit by the knockback and drifts slightly before hovering in the spot it is pushed to.

**Comment by SandwichHorror** [comment]
All pteras remain flying right above where they were summoned on latest hotfix 1.2.1
![2020-10-21_15 51 10](https://user-images.githubusercontent.com/59847281/96775823-16a7bf80-13b6-11eb-9407-8b53c89be49f.png)

**Comment by FuGu0416** [comment]
Should already been fixed in the current version
