### ISSUE TITLE
[Bug][1.2.1]Pteras Carrying Mobs Sink Underground

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#38]
When the mob a Ptera is carrying gets damaged beyond a certain point, the ptera sinks underground, suffocating the mob and frequently causing the ptera itself to suffocate.

**Comment by SandwichHorror** [comment]
Still occurs on latest hotfix
![2020-10-21_15 51 01](https://user-images.githubusercontent.com/59847281/96775776-055eb300-13b6-11eb-93d2-33b3dc26cfd3.png)

**Comment by Avlyssna** [comment]
Seems like there's no logic for the mob to dismount. I'll look into adding something for that.

**Comment by FuGu0416** [comment]
Should already been fixed in the current version
