### ISSUE TITLE
[Suggestion][1.2.1] More Ptera "Passenger" Config Options

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#39]
Pteras carrying mobs is a fun feature, but can be a bit strange or frustrating without greater configuration options available. I've listed my requests hopefully in order of how hard they'd be to implement, with the easiest first.

First, an option to enable or disable the passengers would be simplest of all to implement (I hope).

2nd: An option to set at what difficulty this occurs (1, 2, or 3 for Easy, Medium, Hard)

3rd: An option to set the chance a ptera spawns carrying a mob at all. (A setting of 1 means 1% of pteras carry mobs; a value of 100 means a ptera will always spawn carrying a mob).

4th: An option to set WHICH mobs a ptera can spawn carrying, which includes the default mobs. (If someone wants to remove the creeper spawn because they don't like it, this would allow them to do so. If certain modded mobs might cause the game to glitch out, then simply provide a warning: "May not be compatible with modded entities". It should be up to the users to figure out which mobs are compatible, not you. You'd already be doing a great service by providing such a customizable feature.)

5th (Most Complex Suggestion): An option to set which mobs a ptera can spawn carrying, with additional arguments of entity weight and dimension. In my modpack for example, we have Pteras spawn in large flocks in the Aether. There are no zombies or creepers here, and with the large spawn values, there'd be tons of creepers and zombies all over the place, which doesn't fit with the setting. This would allow us to have pteras carry those mobs only in the Overworld, or even carry Aether-specific monsters when in the Aether only.

modname:entity, weight of this entity being chosen , valid dimension IDs (single = 1 number, multiple = array)

For example:

    \# Customize the mobs carried by a Ptera. Ex. "mod_lavacow:foglet,4,0" or "minecraft:zombie,20,[0,1,-1]" 
    S:"spawn list for ptera passenger" <

In this example, the zombie has a very high comparative weight of being chosen, and the ptera can spawn carrying a zombie in all of the vanilla dimensions. Pteras can only spawn carrying foglets in the overworld.

**Comment by FuGu0416** [comment]
feature 1~4th were added in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/7b361374f0cd62a7742a1fe95793439719faeca9
