### ISSUE TITLE
[Suggestion] Banshee Scream damage source change & further banshee config options

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#41]
First off (and this would've gotten its own issue page, but I've already made SO many), I would be SO happy if the banshee's scream could use a new damageSource besides "mob".  

I personally think either "indirectMagic" or "Magic" would be very fitting. The banshee produces a terrifying scream, powerful enough to kill, so I think it's reasonably magical - and making the damage source reflect that would allow it to better interact with mods that have features related to magic damage (such as taking reduced or increased magic damage, mobs immune to magic can't be harmed by the banshee, etc).

Additionally, this could allow a new config option to change the separate attack strength of banshee's "melee" and "scream" attacks. 

I wouldn't have needed to make this issue, but since its melee attack and scream both use the "mob" damage source, I can't make its scream devastating (say, 30+ damage) without also letting it casually 1-shot most mobs with its normal melee attack, which is definitely not intended or fair.

Further options that would be neat to see:

- Config to control radius of banshee's scream (By default the radius seems a little small - especially since it now sometimes hovers a bit above its target, it often misses the scream even when its target doesn't move).

{Very Ambitious, No Big Deal if you don't want to do this}
- Config to control potion effects the banshee's scream inflicts (potion,amplifier,duration | default - minecraft:weakness,2,7)
Would allow users to create scenarios such as minecraft:wither,0,10 to make the scream "wither away" at your soul, or applying PotionCore's "broken armor" potion effect to have it shatter your defenses.

**Comment by FuGu0416** [comment]
radius config is added in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/5ef9cbc6692cd770061efa397b6f873dd6d95655

as for control potion effects, I'll probably stay fixed cause I believe it would be too complicated for other users to alter that.
