### ISSUE TITLE
[Bug]Golden Heart Bauble + Mending Not Working

### ISSUE THREAD

**Issue by nyctodarkmatter** [FuGu0416/Fishs_Undead_Rising#42]
Likely a simple fix, the Golden Heart does not work with the Mending enchantment while in a Baubles slot. It does work in the main/off-hand, just not in the Baubles slot. While in a Baubles slot XP goes to the player normally, but while in the off-hand it mends the heart as intended. Would appreciate a hotfix for this if possible!

**Comment by FuGu0416** [comment]
That sounds more like a issue between vanilla mending enchantment and Baubles mod.

**Comment by FuGu0416** [comment]
Similar issue:
https://github.com/DreenDex/ImprovedBackpacks-Issues/issues/5

**Comment by nyctodarkmatter** [comment]
@FuGu0416 Spoke with Fish on Discord and let him know that this has been fixed by other mod creators, see Colytra as an example. It does seem like something Baubles should fix, however it is clearly fixable.
https://github.com/TheIllusiveC4/Colytra/issues/2

**Comment by FuGu0416** [comment]
Fixed in the commit https://github.com/FuGu0416/Fishs_Undead_Rising/commit/b8b7eb64c737e16cb3d507cdcc1ed62b76e1f318
