### ISSUE TITLE
[Bug][1.2.1] Banshee scream DamageSource does not have true source

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#43]
I greatly appreciate the scream becoming magic damage. However, this scream is not properly registered to the true source of the banshee, which means death messages will be incorrect, and using other mods to apply effects to the banshee's scream or make other entities immune to the banshee's scream will not be possible (since as far as the game is concerned, the scream damage did not come from the banshee).

**Comment by SandwichHorror** [comment]
![2020-10-21_15 07 30](https://user-images.githubusercontent.com/59847281/96773437-80be6580-13b2-11eb-9f1b-bffe995baacd.png)

note: "true source: null"

**Comment by FuGu0416** [comment]
fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/5ef9cbc6692cd770061efa397b6f873dd6d95655
