### ISSUE TITLE
[BUG] spawn eggs showing blank + mobs not spawning

### ISSUE THREAD

**Issue by Xaurii** [FuGu0416/Fishs_Undead_Rising#45]
edit - oops submitted early
While playing minecraft with friends on a custom modpack, We added this mod as a means of getting moogma's, for a lava supply.
after adding it, no mobs from this mod are spawning naturally, and all spawn eggs are showing as "Spawn" blank.
I'll attach a photo if possible

**Comment by Xaurii** [comment]
![image](https://user-images.githubusercontent.com/53994905/96774950-a7bd6d00-139b-11eb-91d2-d0d16989a6f4.png)
all the items under @undead or @fish are here
all potions are titled as "uncraftable" 
all spawn eggs are "spawn" and all books are simply "enchanted book"

**Comment by FuGu0416** [comment]
I'll need your mod list or modpack so I can try to recreate this issue.

**Comment by Xaurii** [comment]
> I'll need your mod list or modpack so I can try to recreate this issue.

https://drive.google.com/file/d/1bbEZEA6xkcl6wX2eO-kU973XX5yV984X/view?usp=sharing
here is a link to the modpack we've been playing with via the twitch launcher.

**Comment by FuGu0416** [comment]
Should already been fixed in the current version
