### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by dazadazu** [FuGu0416/Fishs_Undead_Rising#47]
Supposedly the Banshee, I have lycanite mobs so forth...

[crash-2020-10-26_23.51.50-server.txt]
(https://github.com/FuGu0416/Fishs_Undead_Rising/files/5443473/crash-2020-10-26_23.51.50-server.txt)

**Comment by FuGu0416** [comment]
There is a newer 1.2.1 version (submitted at 10/19) on the Curseforge that fixes this issue.
