### ISSUE TITLE
Crash, certain mobs? Banshee

### ISSUE THREAD

**Issue by dazadazu** [FuGu0416/Fishs_Undead_Rising#48]
I've tried disabling them by setting their spawn to 0 but crashes still continue. This is the best monster mob out there. 

[crash-2020-10-28_04.34.58-server (1).txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/5455889/crash-2020-10-28_04.34.58-server.1.txt)

**Comment by FuGu0416** [comment]
Did you try re-download the jar file again? It seems that you're using the old 1.2.1 version.

**Comment by FuGu0416** [comment]
Also try setting Avaton's spawn rate to 0 instead of Banshee's

**Comment by dazadazu** [comment]
[crash-2020-10-31_17.18.24-server (1).txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/5472524/crash-2020-10-31_17.18.24-server.1.txt)


So now its the wendigo? Which is very unfortunate to disable two mobs from this mod considering each and every mob in this mod are amazing and it sucks not to hang out with them.

**Comment by FuGu0416** [comment]
Pretty sure that's nothing to do with the Wendigo

similar issues:
https://github.com/Alex-the-666/Ice_and_Fire/issues/2095
https://github.com/HellFirePvP/AstralSorcery/issues/1413

**Comment by dazadazu** [comment]
Mmmm so are you suggesting I remove performant and re-enable those two mobs back? Cause I'll do anything for you mod.

**Comment by FuGu0416** [comment]
Avaton's issue is already fixed in the latest 1.2.1 version, be sure to download again from the Curseforge.

As for Wendigo, I believe remove performat would do.
