### ISSUE TITLE
[Suggestion] Parasite Host Config

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#50]
In addition to the parasite spawn rate, it would be lovely to have a configurable list of mobs that parasites can spawn from in the first place. For example, I'd like to remove the parasites from zombie pigmen but add them to spiders. I'm sure this would be appreciated!

**Comment by Druwan-ctrl** [comment]
Oh yes, i tried doing this with crafttweaker with no success! It would be AWESOME since parasites can justify why undead are a thing and give many storytelling opportunities!
