### ISSUE TITLE
"underminer"s everywhere

### ISSUE THREAD

**Issue by Rey-Alt4Tetra** [FuGu0416/Fishs_Undead_Rising#51]
There are an insane amount of mod_lavacow:underminer entities covering every inch of my worlds. There doesn't appear to be a config for them, so I can only assume this is a bug. They are fully functional, but there are so many of them that I can't test whether other spawns are working.

**Comment by FuGu0416** [comment]
fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/70dd3697983692c8af2ccfbda9d8e129568acdc9
