### ISSUE TITLE
[bug] Ptera, Ingheta and undertakers are overflowing the End

### ISSUE THREAD

**Issue by GalemFulgur** [FuGu0416/Fishs_Undead_Rising#55]
Wandering in the end and fighting the Ender dragon is already a bit tricky. but now, those 3 mobs are spawning in masses in the End, making it impossible to fight the Ender dragon without being in peaceful mode…
And now, those freaks are harassing me in my journey to the end-city!
I checked, and the version of the mod that I'm currently using was supposed to fix this problem (for the nether at least),... but it doesn't.
Also, the spawn rate config doesn't seem to change anything.
It won't kill me if I can't go to the end City, but it would be a pity…
Thank you a lot in advance.

**Comment by FuGu0416** [comment]
You have to clear the mobs that already spawned in the end manually. After the purge, those 3 mobs should not spawn in the end anymore.

Try command like:
/kill @e[type=mod_lavacow:zombiefrozen] 
/kill @e[type=mod_lavacow:ptera] 
/kill @e[type=mod_lavacow:undertaker]
