### ISSUE TITLE
[Bug] Osvermis spams sounds with champions installed

### ISSUE THREAD

**Issue by mxnmnm** [FuGu0416/Fishs_Undead_Rising#58]
I have champions installed and an osvermis became a champion and then spammed the digging sound. I think it has to do with the effects it had. Here is a screenshot

![2020-12-19_22 18 43](https://user-images.githubusercontent.com/8508976/102706635-8fa58500-4248-11eb-996c-de5eda15dbef.png)

This osvermis was definitely the culprit because after I killed him the sounds stopped

**Comment by mxnmnm** [comment]
It seems to happen regardless of the effect

**Comment by Ameranth** [comment]
In my experience this is specifically with the Molten affix; if you blacklist molten for osvermis you should find this "solved."

**Comment by FuGu0416** [comment]
Fixed in the latest 1.2.4 version.

Download Link:
https://www.curseforge.com/minecraft/mc-mods/fishs-undead-rising/files/3282949
