### ISSUE TITLE
[1.12.2] Support for the Enchantment Descriptions Mod

### ISSUE THREAD

**Issue by WolfBV** [FuGu0416/Fishs_Undead_Rising#6]
![Screen Shot 2020-08-02 at 4 07 58 PM](https://user-images.githubusercontent.com/47493126/89134475-6b841a00-d4da-11ea-86d3-7571f91379a0.png)
![Screen Shot 2020-08-02 at 4 08 04 PM](https://user-images.githubusercontent.com/47493126/89134477-6f17a100-d4da-11ea-9c0d-d684bc3a79cf.png)
![Screen Shot 2020-08-02 at 4 08 09 PM](https://user-images.githubusercontent.com/47493126/89134478-6fb03780-d4da-11ea-9ad7-5e139fd291b6.png)

Link to the mod: https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

**Comment by democat3457** [comment]
Already added. #2
