### ISSUE TITLE
[Crash][Compatibility][1.2.3] Ticking Entity on server with Scaling Health

### ISSUE THREAD

**Issue by faeldray** [FuGu0416/Fishs_Undead_Rising#63]
I've been play-testing a modpack I'm making with my boyfriend on a server and we've come across what seems to be a compatibility issue between this mod and Scaling Health.

If the difficulty affects mob health and is set to increase the more players that are around, it sometimes causes crashes. I've noticed that if only one of us is in the area, everything is fine. If the other arrives in the same area though, the server crashes. The same applies if we're trying to join the server again and we were near each other; one person joining is fine, but the server crashes when the other joins as well.

I've disabled the difficulty increase setting for now and we've had no more crashes since. I should note that mobs from other mods do not cause this problem.

Here are the crash reports:
https://pastebin.com/ZUHbshfn
https://pastebin.com/WkKdx0Vr

**Comment by Avlyssna** [comment]
It appears that the mob's attack target isn't being checked properly before use. This basically means that in cases like yours there is no target for the mob to attack, but it tries to attack it anyways: leading to a crash.

I'll see about submitting a pull request to fix these two instances.

**Comment by FuGu0416** [comment]
Thanks for the fix, I'll check if there were any other missing condition checking.
