### ISSUE TITLE
[1.2.3] Increasing Untertaker health in config does not work correctly

### ISSUE THREAD

**Issue by HariboTer** [FuGu0416/Fishs_Undead_Rising#74]
As the title says - I increased their maximum health in the config file to 240, but ingame newly spawned untertakers are stuck at 60. For Avaton, Banshee, Scarecrow and Undead Swine similar modifications worked as expected, so I presume something is bugged in regards to the Undertaker.

**Comment by Avlyssna** [comment]
I'll take a look into the issue sometime this week. Thanks for the notice.
