### ISSUE TITLE
[1.2.3] Osvermis Ranged Attack Stop/Start Spam

### ISSUE THREAD

**Issue by Ameranth** [FuGu0416/Fishs_Undead_Rising#76]
When maintaining a distance of roughly 15 blocks from an Osvermis, they will spam their attack sound/animation--without actually firing a projectile--as they slowly move toward the player.

Tested with Undead Rising as the only mod running.

To reproduce:
 - Spawn an osvermis.
 - Slowly move toward it, maintaining roughly 15 blocks of distance.
 - Once it notices you and tries to attack, maintain distance by backing away slowly as it moves toward you, the spam will be obvious.

**Comment by FuGu0416** [comment]
Fixed in the latest 1.2.4 version.

Download Link:
https://www.curseforge.com/minecraft/mc-mods/fishs-undead-rising/files/3282949
