### ISSUE TITLE
[1.2.3] [Bug] Salamander Taming/Growth

### ISSUE THREAD

**Issue by ShareTheVoid** [FuGu0416/Fishs_Undead_Rising#78]
While growing my tamed Salamander Spawn, I noticed that as soon as it reached its adult/ridable stage, it began taking excessive damage and died shortly afterwards.  I attempted to grow another, and the same thing happened.  I think this may be an issue with the hitbox of the adult tamed Salamander, likely the hitbox clipping through the floor and triggering the suffocation.  Another thing I noted was that the Salamander continually moved backwards, but only up to a point.  It stood further away and backed away when I tried to approach it, but still followed me when I backed up.  It also only suffocated in certain areas and was still ridable, but met several seemingly invisible barriers and rubber banded at a very fast speed upon falling downwards even a single block's height.  Is anyone else experiencing this issue???

**Comment by FuGu0416** [comment]
This should be fixed in the latest 1.2.4 version.

Download Link:
https://www.curseforge.com/minecraft/mc-mods/fishs-undead-rising/files/3282949
