### ISSUE TITLE
Glow Mushroom removes bedrock

### ISSUE THREAD

**Issue by Kompreya** [FuGu0416/Fishs_Undead_Rising#80]
Version: 1.2.0 (1.12)

Issue: Bonemealing a glow mushroom replaces the block underneath it with podzol. There is no limit to what blocks this replaces, including bedrock and other unbreakable blocks.

Steps to reproduce:
1) Place a glow mushroom on desired block to 'delete'
2) Bonemeal glow mushroom
3) Glow mushroom turns the two blocks under it into podzol/tombstone
4) Break the podzol

Suggested fix:
Either a blacklist config of what blocks glow mushrooms can/cant be placed on, or config to disable glow mushrooms from making graves (or both!)

**Comment by FuGu0416** [comment]
Bonemealing a glowshroom into a cemetery is a bug and that issue was already fixed in 1.2.1.
Just update to the newest version and it should never happened again.
