### ISSUE TITLE
Killed Zombie Villager on Boat Crashes Server

### ISSUE THREAD

**Issue by MinicomSoftware** [FuGu0416/Fishs_Undead_Rising#82]
One of my players created had a villager on a boat, it turned into a zombie villager, then it was killed which then resulted in the following crash. The player can no longer load into the chunk as it keeps crashing the entire server. I removed this mod, destroyed the boat, and installed it back in and it's fine now. Here is the bug report:

[bug.txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/6094204/bug.txt)

**Comment by FuGu0416** [comment]
Fixed in the latest 1.2.4 version.

Download Link:
https://www.curseforge.com/minecraft/mc-mods/fishs-undead-rising/files/3282949
