### ISSUE TITLE
Azrael's Scythe uses durability when right-clicking.

### ISSUE THREAD

**Issue by rougedarkdragon** [FuGu0416/Fishs_Undead_Rising#83]
I crafted the Azrael's Scythe in a survival world and noticed that it uses durability when the player right-clicks. Losing durability on a powerful weapon by right clicking is rather frustrating. Please fix this.

**Comment by FuGu0416** [comment]
Fixed in the latest 1.2.4 version.

Download Link:
https://www.curseforge.com/minecraft/mc-mods/fishs-undead-rising/files/3282949
