### ISSUE TITLE
[1.2.3][BUG] Parasite Incompatibility with Electroblob's wizardry(ElectroblobsWizardry-4.3.4-MC1.12.2) Bubble Spell

### ISSUE THREAD

**Issue by Osvetamp4** [FuGu0416/Fishs_Undead_Rising#84]
Whenever the player or a wizard uses the bubble spell to target a parasite, the game crashes. Logging back into the world will keep crashing as long as the parasite still exists and is affected by the bubble spell.

**Comment by Osvetamp4** [comment]
This bug basically locks down my entire world. I tried to set the world to peaceful mode using the level.dat file to get rid of the parasite. It didn't work. I can't do anything about it :/

**Comment by Osvetamp4** [comment]
[crash-2021-04-08_16.11.50-server.txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/6285361/crash-2021-04-08_16.11.50-server.txt)

**Comment by FuGu0416** [comment]
Fixed in the latest 1.2.4 version.

Download Link:
https://www.curseforge.com/minecraft/mc-mods/fishs-undead-rising/files/3282949
