### ISSUE TITLE
Crash on startup for version 1.2.4 [1.12.2] - NoClassDefFoundError

### ISSUE THREAD

**Issue by MinicomSoftware** [FuGu0416/Fishs_Undead_Rising#86]
I get the following error when booting up my server (note: all I changed was the version of this mod from 1.2.3 -> 1.2.4).

[crash-2021-04-20_11.17.05-server.txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/6345821/crash-2021-04-20_11.17.05-server.txt)

**Comment by FuGu0416** [comment]
The newest version should fix this issue.
https://www.curseforge.com/minecraft/mc-mods/fishs-undead-rising/files/3283582
