### ISSUE TITLE
Dupe bug with potioncore

### ISSUE THREAD

**Issue by mxnmnm** [FuGu0416/Fishs_Undead_Rising#89]
Giving a mimicrab the potion effect revival allows you to dupe items. 

Step 1: Drop item you want to dupe in front of mimicrab
Step 2: Give mimicrab revival potion effect
Step 3: Kill mimicrab once
Step 4: Collect item or let mimicrab collect it
Step 5: Rinse and repeat or kill mimicrab

**Comment by FuGu0416** [comment]
The revival effect comes from which mod?

**Comment by FuGu0416** [comment]
Fixed in the branch f75a1b0
