### ISSUE TITLE
[suggestion][1.12.2] Spawn control

### ISSUE THREAD

**Issue by FerriFinder** [FuGu0416/Fishs_Undead_Rising#9]
I have BetterNether installed which gives the nether a very overgrown and chaotic feel which I think would be nicely complemented by some Undead Rising mobs such as the ciuperca. Unfortunantly, unlike other mob adding mods which gives you the option of applying new spawning rules such as which dimensions and biomes the mobs spawn in, I haven't been able to find any such settings in the Undead Rising config file. Would be much appreciated if you consider adding this feature in the future.

**Comment by FuGu0416** [comment]
I'll add a dimension allow list in the next update. As of biome, I'll suggest using other mods to control spawn since it is a bit of too complicated unless the player is familiar with Forge's biome dictionary.

**Comment by FerriFinder** [comment]
> 
> 
> I'll add a dimension allow list in the next update. As of biome, I'll suggest using other mods to control spawn since it is a bit of too complicated unless the player is familiar with Forge's biome dictionary.

Any specific recommendations? Some of my installed mods use mob libraries (ex. Multimob, CustomSpawner) with excellent config files, but the undead mobs do not appear in their spawn lists. I've heard about a mod called In "Control!" which has that kind of capability, but I don't have the coding experience required to use it.

**Comment by FerriFinder** [comment]
Knob control doesn't seem to work with modded mobs. Strange because that seems like kinda the whole point. Their issue reporting is terrible though, I can't get any help.

**Comment by FuGu0416** [comment]
They have a Discord server. Maybe your can submit your issue there and see if anyone could provide some help.
