### ISSUE TITLE
Banshees get stuck in trees - Pathing

### ISSUE THREAD

**Issue by Keaft** [FuGu0416/Fishs_Undead_Rising#91]
Help! Call the fire department my Banshee is stuck up in a tree!

But on a more serious note, I've used McJty's In Control! mod to spawn the Banshees in the Ominous Forest from Biomes O' Plenty. They tend to wander for a short period and then "climb" up into trees and get stuck. At first I thought it was climbing the vines growing on the trees, but even trees without vines they seem to get stuck in.

After testing it appears that it's a pathing problem. I tried pushing the Banshee and it kept going the same direction. I deleted blocks in it's way until it could get where it was trying to go and sure enough it finally changed where it wanted to go.

Forge: 14.23.5.2855.
Fish's Undead Rising: 1.3.0.
Biomes O' Plenty: 1.12.2-7.0.1.2441-universal.
Realistic Terrain Generation: 1.12.2-6.1.0.0-snapshot.1.
Climate Control/Geographicraft 1.12-0.8.9b.
![image](https://user-images.githubusercontent.com/68153/124402956-c036a300-dcf0-11eb-9e43-f8fdf174ed9c.png)

**Comment by FuGu0416** [comment]
Fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/73c1c3c64052d838fc7d4f36cfe0cfce38f46458
