### ISSUE TITLE
Skeleton AI Broken

### ISSUE THREAD

**Issue by isaaachipkiss** [FuGu0416/Fishs_Undead_Rising#92]
Skeletons won't shoot the player if they are across a gap. I've tested it by using the mod versions on backups of the same world and the results are consistent, I'm thinking that this mod changes skeleton pathfinding.

**Comment by FuGu0416** [comment]
Fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/73c1c3c64052d838fc7d4f36cfe0cfce38f46458
