### ISSUE TITLE
[1.12.2] Strange crash with picking up parasites

### ISSUE THREAD

**Issue by throaway123869** [FuGu0416/Fishs_Undead_Rising#93]
[crash-2021-10-31_11.35.42-client.txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/7449256/crash-2021-10-31_11.35.42-client.txt)
Crash occurs when right-clicking a parasite mob to pick it up.  Didn't always occur, and it only happened with one parasite entity.  I've had it happen before, though.  Might be important to note, I've renamed them to Leeches in the name file.

**Comment by throaway123869** [comment]
[crash-2021-10-31_11.41.21-server.txt](https://github.com/FuGu0416/Fishs_Undead_Rising/files/7449263/crash-2021-10-31_11.41.21-server.txt)
This error also occurred, but the game did not crash.  The item was picked up successfully.

**Comment by FuGu0416** [comment]
Fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/73c1c3c64052d838fc7d4f36cfe0cfce38f46458
