### ISSUE TITLE
[BUG]Error with the Raven's Flying Animations

### ISSUE THREAD

**Issue by TheMagicalSC** [FuGu0416/Fishs_Undead_Rising#98]
The wings seem to rotate through the body as apposed to properly flapping.

**Comment by FuGu0416** [comment]
Should already been fixed in the current version

**Comment by FuGu0416** [comment]
fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/df77764350a836443c4c89d20df283f7e3a6288f
