### ISSUE TITLE
Skeleton (minions) from other mods losing their target selector AI

### ISSUE THREAD

**Issue by WinDanesz** [FuGu0416/Fishs_Undead_Rising#99]
FUR version: 1.3.1
Other mods involved: Electroblob's Wizardry (or any other mod adding skeleton minions which are instanceof AbstractSkeleton)

A few users of Electroblob's Wizardry's skeleton summoning spells have reported that their various skeleton minions (new entities added by Wizardry) stopped engaging targets. The issue is present when FUR v1.3.1 is installed. After a quick glance, I'm suspecting that [this logic in ModEventHandler](https://github.com/FuGu0416/Fishs_Undead_Rising/blob/b66ffbdb123383386189998a72b45379a47cd734/Forge1.12.2/src/main/java/com/Fishmod/mod_LavaCow/util/ModEventHandler.java#L641-L665) causes the problem as it's purging the target selector of any entities. This logic might be feasible where only FUR is installed, but it will probably interfere with any other mods adding skeletons, especially those which are minions owned by players. I haven't done any further testing, but extending the filter by an additional check would probably help for most of these mods, e.g.:
`if(event.getEntity() != null && event.getEntity() instanceof AbstractSkeleton && !(event.getEntity() instanceof IEntityOwnable && ((IEntityOwnable) event.getEntity()).getOwnerId() != null)) {`

**Comment by FuGu0416** [comment]
2.0.0 for Minecraft 1.16.5 should fix this issue.
I'll update another fix for Minecraft 1.12.2

**Comment by FuGu0416** [comment]
Should be fixed in https://github.com/FuGu0416/Fishs_Undead_Rising/commit/31ecc9ccef99f1ba5967a02529d9d7c6b9337c11
